// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yyqgktgfvlpolrtaaice.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl5cWdrdGdmdmxwb2xydGFhaWNlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxOTQzMzgsImV4cCI6MjA2NTc3MDMzOH0.ANLByhlxfJfNPeyGwew50EumJ1EyBC9xh-M_wCfJ8LY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);