"""Add analytics auth fields to social_connections

Revision ID: j0e1f2g3h4i5
Revises: i9d0e1f2g3h4
Create Date: 2025-01-24 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'j0e1f2g3h4i5'
down_revision = 'i9d0e1f2g3h4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('social_connections', sa.Column('analytics_access_token', sa.String(), nullable=True))
    op.add_column('social_connections', sa.Column('analytics_refresh_token', sa.String(), nullable=True))
    op.add_column('social_connections', sa.Column('analytics_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('social_connections', sa.Column('analytics_scope', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('social_connections', 'analytics_scope')
    op.drop_column('social_connections', 'analytics_expires_at')
    op.drop_column('social_connections', 'analytics_refresh_token')
    op.drop_column('social_connections', 'analytics_access_token')
    # ### end Alembic commands ###
