"""Schemas module."""

from .auth import (
    UserCreate,
    UserLogin,
    UserResponse,
    AuthResponse,
    TokenResponse,
    RefreshTokenRequest,
    GoogleAuthRequest,
    GoogleSignInWithToken,
    PasswordResetRequest,
    SuccessResponse,
)
from .content import (
    ContentIdeaCreate,
    ContentIdeaUpdate,
    ContentIdeaResponse,
    ContentIdeaListResponse,
    UserPreferencesCreate,
    UserPreferencesUpdate,
    UserPreferencesResponse,
    SocialConnectionCreate,
    SocialConnectionUpdate,
    SocialConnectionResponse,
    WritingStyleAnalysisCreate,
    WritingStyleAnalysisUpdate,
    WritingStyleAnalysisResponse,
    ImportedContentCreate,
    ImportedContentResponse,
    ScrapedContentCreate,
    ScrapedContentResponse,
    SuggestedPostCreate,
    SuggestedPostResponse,
    SubstackData,
    SubstackConnectionData,
    SubstackAnalysisResponse,
    WritingStyleData,
    PostingPatterns,
    EngagementInsights,
    PlatformAnalysisData,
    PlatformAnalysisResponse,
)

__all__ = [
    # Auth schemas
    "UserCreate",
    "UserLogin",
    "UserResponse",
    "AuthResponse",
    "TokenResponse",
    "RefreshTokenRequest",
    "GoogleAuthRequest",
    "GoogleSignInWithToken",
    "PasswordResetRequest",
    "SuccessResponse",
    # Content schemas
    "ContentIdeaCreate",
    "ContentIdeaUpdate",
    "ContentIdeaResponse",
    "ContentIdeaListResponse",
    "UserPreferencesCreate",
    "UserPreferencesUpdate",
    "UserPreferencesResponse",
    "SocialConnectionCreate",
    "SocialConnectionUpdate",
    "SocialConnectionResponse",
    "WritingStyleAnalysisCreate",
    "WritingStyleAnalysisUpdate",
    "WritingStyleAnalysisResponse",
    "ImportedContentCreate",
    "ImportedContentResponse",
    "ScrapedContentCreate",
    "ScrapedContentResponse",
    "SuggestedPostCreate",
    "SuggestedPostResponse",
    "SubstackData",
    "SubstackConnectionData",
    "SubstackAnalysisResponse",
    "WritingStyleData",
    "PostingPatterns",
    "EngagementInsights",
    "PlatformAnalysisData",
    "PlatformAnalysisResponse",
]
