name: Terraform Deploy Cloud Run

on:
  workflow_call:
    inputs:
      environment:
        description: "Environment (staging/production)"
        required: true
        type: string
      image_tag:
        description: "Docker image tag to deploy (required for apply). e.g. main-9a56f6c"
        required: false
        type: string
    outputs:
      service_url:
        description: "The URL of the deployed Cloud Run service."
        value: ${{ jobs.terraform.outputs.service_url }}
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment (staging/production)"
        required: true
        default: "staging"
        type: choice
        options:
          - staging
          - production
      action:
        description: "Terraform action"
        required: true
        default: "plan"
        type: choice
        options:
          - plan
          - apply
          - destroy
      image_tag:
        description: "Docker image tag to deploy (required for apply). e.g. main-9a56f6c"
        required: false
        type: string

env:
  TF_VAR_project_id: ${{ secrets.GCP_PROJECT_ID }}
  TF_VAR_region: ${{ secrets.GCP_REGION }}
  TF_VAR_environment: ${{ github.event.inputs.environment }}

jobs:
  terraform:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    outputs:
      service_url: ${{ steps.tf_output.outputs.service_url || steps.tf_output_no_changes.outputs.service_url }}

    permissions:
      contents: read
      id-token: write

    defaults:
      run:
        working-directory: ./terraform/environments/${{ github.event.inputs.environment }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Authenticate to Google Cloud (Keyless)
        uses: "google-github-actions/auth@v2"
        with:
          workload_identity_provider: ${{ secrets.GCP_WIF_PROVIDER }}
          service_account: ${{ secrets.GCP_TERRAFORM_SA_EMAIL }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Terraform Init
        run: terraform init && terraform state pull

      - name: Terraform Plan
        id: plan
        run: |
          IMAGE_TAG_VAR=""
          if [ -n "${{ github.event.inputs.image_tag }}" ]; then
            IMAGE_TAG_VAR="-var=image_tag=${{ github.event.inputs.image_tag }}"
          fi
          terraform plan -detailed-exitcode -out=tfplan -var="manage_cloud_run_service=true" $IMAGE_TAG_VAR
          echo "plan_exitcode=$?" >> $GITHUB_OUTPUT

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan

      - name: Set Terraform Outputs
        id: tf_output
        run: |
          echo "service_url=$(terraform output -raw cloud_run_service_url)" >> $GITHUB_OUTPUT

      - name: Get Terraform Outputs (No Changes)
        id: tf_output_no_changes
        run: |
          # When there are no changes, still get the current service URL from state
          SERVICE_URL=$(terraform output -raw cloud_run_service_url 2>/dev/null || echo "")
          if [ "$SERVICE_URL" != "n/a" ] && [ -n "$SERVICE_URL" ]; then
            echo "service_url=$SERVICE_URL" >> $GITHUB_OUTPUT
          else
            echo "service_url=" >> $GITHUB_OUTPUT
            echo "⚠️ No Cloud Run service found in current state"
          fi
